//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Infrastructure.;

//#nullable disable

//namespace RestaurantManagement.Migrations
//{
//    [DbContext(typeof(RestaurantContext))]
//    partial class RestaurantContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.9")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("RestaurantManagement.Models.Category", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasMaxLength(300)
//                        .HasColumnType("nvarchar(300)");

//                    b.Property<int>("DisplayOrder")
//                        .HasColumnType("int");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<bool>("IsDeleted")
//                        .HasColumnType("bit");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("Categories");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "All types of pizza",
//                            DisplayOrder = 1,
//                            IsActive = true,
//                            IsDeleted = false,
//                            Name = "Pizza"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Juicy grilled burgers",
//                            DisplayOrder = 2,
//                            IsActive = true,
//                            IsDeleted = false,
//                            Name = "Burgers"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Italian pasta dishes",
//                            DisplayOrder = 3,
//                            IsActive = true,
//                            IsDeleted = false,
//                            Name = "Pasta"
//                        },
//                        new
//                        {
//                            Id = 4,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Soft drinks and beverages",
//                            DisplayOrder = 4,
//                            IsActive = true,
//                            IsDeleted = false,
//                            Name = "Drinks"
//                        },
//                        new
//                        {
//                            Id = 5,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Sweet desserts",
//                            DisplayOrder = 5,
//                            IsActive = true,
//                            IsDeleted = false,
//                            Name = "Desserts"
//                        });
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.Customer", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Address")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsDeleted")
//                        .HasColumnType("bit");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Phone")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("Customers");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Address = "Cairo",
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            Name = "Ahmed Ali",
//                            Phone = "0101000001"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            Address = "Giza",
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            Name = "Sara Mohamed",
//                            Phone = "0101000002"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            Address = "Alexandria",
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            Name = "Khaled Hassan",
//                            Phone = "0101000003"
//                        });
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.MenuItem", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CategoryId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Description")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<string>("ImageUrl")
//                        .HasMaxLength(250)
//                        .HasColumnType("nvarchar(250)");

//                    b.Property<bool>("IsAvailable")
//                        .HasColumnType("bit");

//                    b.Property<bool>("IsDeleted")
//                        .HasColumnType("bit");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<int?>("OrderId")
//                        .HasColumnType("int");

//                    b.Property<int>("PreparationTime")
//                        .HasColumnType("int");

//                    b.Property<decimal>("Price")
//                        .HasColumnType("decimal(18,2)");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("CategoryId");

//                    b.HasIndex("OrderId");

//                    b.ToTable("MenuItems");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            CategoryId = 1,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Classic cheese pizza",
//                            IsAvailable = true,
//                            IsDeleted = false,
//                            Name = "Margherita Pizza",
//                            PreparationTime = 0,
//                            Price = 120m
//                        },
//                        new
//                        {
//                            Id = 2,
//                            CategoryId = 1,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Spicy pepperoni and cheese",
//                            IsAvailable = true,
//                            IsDeleted = false,
//                            Name = "Pepperoni Pizza",
//                            PreparationTime = 0,
//                            Price = 140m
//                        },
//                        new
//                        {
//                            Id = 3,
//                            CategoryId = 2,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Grilled beef patty with cheese",
//                            IsAvailable = true,
//                            IsDeleted = false,
//                            Name = "Beef Burger",
//                            PreparationTime = 0,
//                            Price = 110m
//                        },
//                        new
//                        {
//                            Id = 4,
//                            CategoryId = 2,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Grilled chicken sandwich",
//                            IsAvailable = true,
//                            IsDeleted = false,
//                            Name = "Chicken Burger",
//                            PreparationTime = 0,
//                            Price = 100m
//                        },
//                        new
//                        {
//                            Id = 5,
//                            CategoryId = 3,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Creamy pasta with chicken",
//                            IsAvailable = true,
//                            IsDeleted = false,
//                            Name = "Fettuccine Alfredo",
//                            PreparationTime = 0,
//                            Price = 130m
//                        },
//                        new
//                        {
//                            Id = 6,
//                            CategoryId = 4,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Cold drink",
//                            IsAvailable = true,
//                            IsDeleted = false,
//                            Name = "Coca Cola",
//                            PreparationTime = 0,
//                            Price = 25m
//                        },
//                        new
//                        {
//                            Id = 7,
//                            CategoryId = 5,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            Description = "Rich chocolate dessert",
//                            IsAvailable = true,
//                            IsDeleted = false,
//                            Name = "Chocolate Cake",
//                            PreparationTime = 0,
//                            Price = 70m
//                        });
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.Order", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime?>("CompletedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("CustomerId")
//                        .HasColumnType("int");

//                    b.Property<string>("CustomerName")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<string>("CustomerPhone")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("DeliveryAddress")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<bool>("IsDeleted")
//                        .HasColumnType("bit");

//                    b.Property<DateTime>("OrderDate")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("OrderType")
//                        .HasColumnType("int");

//                    b.Property<int>("Status")
//                        .HasColumnType("int");

//                    b.Property<decimal>("SubTotal")
//                        .HasColumnType("decimal(18,2)");

//                    b.Property<string>("TableNumber")
//                        .HasMaxLength(10)
//                        .HasColumnType("nvarchar(10)");

//                    b.Property<decimal>("Tax")
//                        .HasColumnType("decimal(18,2)");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("CustomerId");

//                    b.ToTable("Orders");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            CustomerId = 1,
//                            CustomerName = "Ahmed Ali",
//                            CustomerPhone = "0101000001",
//                            IsDeleted = false,
//                            OrderDate = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
//                            OrderType = 0,
//                            Status = 4,
//                            SubTotal = 260m,
//                            TableNumber = "T1",
//                            Tax = 20m
//                        },
//                        new
//                        {
//                            Id = 2,
//                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            CustomerId = 2,
//                            CustomerName = "Sara Mohamed",
//                            CustomerPhone = "0101000002",
//                            IsDeleted = false,
//                            OrderDate = new DateTime(2025, 10, 11, 13, 30, 0, 0, DateTimeKind.Unspecified),
//                            OrderType = 1,
//                            Status = 0,
//                            SubTotal = 100m,
//                            Tax = 8m
//                        },
//                        new
//                        {
//                            Id = 3,
//                            CreatedAt = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            CustomerId = 3,
//                            CustomerName = "Khaled Hassan",
//                            CustomerPhone = "0101000003",
//                            DeliveryAddress = "Some Address",
//                            IsDeleted = false,
//                            OrderDate = new DateTime(2025, 10, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
//                            OrderType = 2,
//                            Status = 4,
//                            SubTotal = 195m,
//                            Tax = 15m
//                        });
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.OrderItem", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsDeleted")
//                        .HasColumnType("bit");

//                    b.Property<int>("MenuItemId")
//                        .HasColumnType("int");

//                    b.Property<int>("OrderId")
//                        .HasColumnType("int");

//                    b.Property<int>("Quantity")
//                        .HasColumnType("int");

//                    b.Property<string>("SpecialRequest")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<decimal>("UnitPrice")
//                        .HasColumnType("decimal(18,2)");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("MenuItemId");

//                    b.HasIndex("OrderId");

//                    b.ToTable("OrderItems");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            MenuItemId = 1,
//                            OrderId = 1,
//                            Quantity = 1,
//                            UnitPrice = 120m
//                        },
//                        new
//                        {
//                            Id = 2,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            MenuItemId = 3,
//                            OrderId = 1,
//                            Quantity = 1,
//                            UnitPrice = 110m
//                        },
//                        new
//                        {
//                            Id = 3,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            MenuItemId = 6,
//                            OrderId = 1,
//                            Quantity = 1,
//                            UnitPrice = 30m
//                        },
//                        new
//                        {
//                            Id = 4,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            MenuItemId = 4,
//                            OrderId = 2,
//                            Quantity = 1,
//                            UnitPrice = 100m
//                        },
//                        new
//                        {
//                            Id = 5,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            MenuItemId = 5,
//                            OrderId = 3,
//                            Quantity = 1,
//                            UnitPrice = 130m
//                        },
//                        new
//                        {
//                            Id = 6,
//                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                            IsDeleted = false,
//                            MenuItemId = 7,
//                            OrderId = 3,
//                            Quantity = 1,
//                            UnitPrice = 65m
//                        });
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.MenuItem", b =>
//                {
//                    b.HasOne("RestaurantManagement.Models.Category", "Category")
//                        .WithMany("MenuItems")
//                        .HasForeignKey("CategoryId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("RestaurantManagement.Models.Order", null)
//                        .WithMany("MenuItems")
//                        .HasForeignKey("OrderId");

//                    b.Navigation("Category");
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.Order", b =>
//                {
//                    b.HasOne("RestaurantManagement.Models.Customer", "Customer")
//                        .WithMany("Orders")
//                        .HasForeignKey("CustomerId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Customer");
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.OrderItem", b =>
//                {
//                    b.HasOne("RestaurantManagement.Models.MenuItem", "MenuItem")
//                        .WithMany("OrderItems")
//                        .HasForeignKey("MenuItemId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("RestaurantManagement.Models.Order", "Order")
//                        .WithMany("OrderItems")
//                        .HasForeignKey("OrderId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("MenuItem");

//                    b.Navigation("Order");
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.Category", b =>
//                {
//                    b.Navigation("MenuItems");
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.Customer", b =>
//                {
//                    b.Navigation("Orders");
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.MenuItem", b =>
//                {
//                    b.Navigation("OrderItems");
//                });

//            modelBuilder.Entity("RestaurantManagement.Models.Order", b =>
//                {
//                    b.Navigation("MenuItems");

//                    b.Navigation("OrderItems");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
